const SELECT_TABLE = "SELECT_TABLE";
const TOGGLE_TABLE = "TOGGLE_TABLE";
const INCREMENT_MONEY_EARN = "INCREMENT_MONEY_EARN";
const ADD_TABLE_ITEM = "ADD_TABLE_ITEM";
const DELETE_TABLE_ITEM = "DELETE_TABLE_ITEM";

module.exports = {
  SELECT_TABLE,
  TOGGLE_TABLE,
  INCREMENT_MONEY_EARN,
  ADD_TABLE_ITEM,
  DELETE_TABLE_ITEM
};
